AWSTemplateFormatVersion: 2010-09-09
Description: This template provisions a sample s3 bucket

# Parameters
Parameters:

  SampleBucketName1:
    Type: String
    Default: ''
  SampleBucketName2:
    Type: String
    Default: ''
  TeamValue:
    Type: String
    Default: 'dev'
    AllowedValues:
      - dev
      - stg
      - prod
  OwnerValue:
    Type: String
    Default: ''
  S3Versioning:
    Type: String
    Default: 'Enabled'
    AllowedValues:
      - Enabled
      - Suspended

# Resources
Resources:

# S3 Bucket
  SampleS3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref SampleBucketName1
      VersioningConfiguration:
        Status: !Ref S3Versioning
      Tags:
      - Key: team
        Value: !Ref TeamValue  
      - Key: owner
        Value: !Ref OwnerValue

# S3 Bucket - 2
  SampleS3Bucket2:
      DependsOn:
      - SampleS3Bucket
      Type: AWS::S3::Bucket
      Properties:
        BucketName: !Ref SampleBucketName2
        VersioningConfiguration:
          Status: !Ref S3Versioning
        Tags:
        - Key: team
          Value: !Ref TeamValue  
        - Key: owner
          Value: !Ref OwnerValue
  
# Outputs
Outputs:
  # SampleBucketName
  SampleBucketName:
    Description: S3 Bucket1 Name
    Value: !Ref SampleS3Bucket1
  SampleBucketName2:
    Description: S3 Bucket2 Name and Region
    Value: 
      Fn::Join:
      - ''
      - - 'bucket:'
        - Ref: AWS::Region
        - ':'
        - Ref: SampleS3Bucket2